### ISSUE TITLE
Snail has left-handed shell (very rare)

### ISSUE THREAD

**Issue by sladen** [Manu343726/snail#7]
The software uses a mascot image filename called `snail.jpg` with the origin reported as:

* _…choose a random animal…_

The mascot picture is of a left-handed snail.  Left-handed snails are extremely rare, with only a handful of identified left-handed snails known and documented world-wide:

* http://www.nottinghampost.com/rare-lefty-snail-jeremy-frozen-out-in-slimy-love-triangle/story-30341484-detail/story.html

A picture of of a left-handed snail would indeed therefore be quite specific, and so not a "a random animal" as the description suggests.

On the other-hand, the mascot image could also be a crop/mirror/flip from a picture of a much more common right-hand snail, of which there would be many to choose from.  For example this photograph of a right-handed Roman Snail, taken by Jiří Bohdal in the Czech Republic:

* http://www.naturephoto-cz.com/roman-snail-photo-1159.html
* http://www.naturephoto-cz.com/photos/others/roman-snail-21963.jpg

In this case, ideally the photographer Jiří Bohdal should be contacted/credited as appropriate, and the description updated to give more details about the snail featured.

This should allow users of `snail` to grow a greater bond with the mascot.

**Comment by Manu343726** [comment]
Thank you very much for such a funny way to report unfair use of media. We have this bad habit of googling stuff with no care at all about the original authors of what we are technically stealing.
